// <auto-generated />
using System;
using AirlineApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace airlineApp.Migrations
{
    [DbContext(typeof(AirlineContext))]
    [Migration("20250619201500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirlineApp.Models.Aircraft", b =>
                {
                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RegistrationNumber");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("AirlineApp.Models.CrewAssignment", b =>
                {
                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FlightId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CrewAssignments");
                });

            modelBuilder.Entity("AirlineApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightHours")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("MedicalCertificateExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AirlineApp.Models.EmployeeTraining", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.HasKey("EventId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeTrainings");
                });

            modelBuilder.Entity("AirlineApp.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftRegistration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AircraftRegistrationNumber")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDeparture")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftRegistrationNumber");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AirlineApp.Models.FlightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ActualDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("DelayReason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<double>("FuelConsumed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightLogs");
                });

            modelBuilder.Entity("AirlineApp.Models.MaintenanceSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("AircraftRegistration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AircraftRegistrationNumber")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("AircraftRegistrationNumber");

                    b.ToTable("MaintenanceSchedules");
                });

            modelBuilder.Entity("AirlineApp.Models.PilotReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ActualDeparture")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelayDuration")
                        .HasColumnType("int");

                    b.Property<string>("DelayReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<double>("FuelUsed")
                        .HasColumnType("float");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TechnicalIssues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeatherNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FlightId");

                    b.ToTable("PilotReports");
                });

            modelBuilder.Entity("AirlineApp.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("AirlineApp.Models.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalReportId");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("AirlineApp.Models.TechnicalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftRegistration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AircraftRegistration");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TechnicalReports");
                });

            modelBuilder.Entity("AirlineApp.Models.TrainingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingEvents");
                });

            modelBuilder.Entity("AirlineApp.Models.CrewAssignment", b =>
                {
                    b.HasOne("AirlineApp.Models.Employee", "Employee")
                        .WithMany("CrewAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirlineApp.Models.Flight", "Flight")
                        .WithMany("CrewAssignments")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineApp.Models.EmployeeTraining", b =>
                {
                    b.HasOne("AirlineApp.Models.Employee", "Employee")
                        .WithMany("EmployeeTrainings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineApp.Models.TrainingEvent", "TrainingEvent")
                        .WithMany("EmployeeTrainings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TrainingEvent");
                });

            modelBuilder.Entity("AirlineApp.Models.Flight", b =>
                {
                    b.HasOne("AirlineApp.Models.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftRegistrationNumber");

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("AirlineApp.Models.FlightLog", b =>
                {
                    b.HasOne("AirlineApp.Models.Flight", "Flight")
                        .WithMany("FlightLogs")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineApp.Models.MaintenanceSchedule", b =>
                {
                    b.HasOne("AirlineApp.Models.Aircraft", "Aircraft")
                        .WithMany("MaintenanceSchedules")
                        .HasForeignKey("AircraftRegistrationNumber");

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("AirlineApp.Models.PilotReport", b =>
                {
                    b.HasOne("AirlineApp.Models.Employee", "Employee")
                        .WithMany("PilotReports")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirlineApp.Models.Flight", "Flight")
                        .WithMany("PilotReports")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineApp.Models.Qualification", b =>
                {
                    b.HasOne("AirlineApp.Models.Employee", "Employee")
                        .WithMany("Qualifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AirlineApp.Models.SparePart", b =>
                {
                    b.HasOne("AirlineApp.Models.TechnicalReport", "TechnicalReport")
                        .WithMany("SpareParts")
                        .HasForeignKey("TechnicalReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnicalReport");
                });

            modelBuilder.Entity("AirlineApp.Models.TechnicalReport", b =>
                {
                    b.HasOne("AirlineApp.Models.Aircraft", "Aircraft")
                        .WithMany("TechnicalReports")
                        .HasForeignKey("AircraftRegistration")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineApp.Models.Employee", "Employee")
                        .WithMany("TechnicalReports")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AirlineApp.Models.TrainingEvent", b =>
                {
                    b.HasOne("AirlineApp.Models.Employee", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("AirlineApp.Models.Aircraft", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("MaintenanceSchedules");

                    b.Navigation("TechnicalReports");
                });

            modelBuilder.Entity("AirlineApp.Models.Employee", b =>
                {
                    b.Navigation("CrewAssignments");

                    b.Navigation("EmployeeTrainings");

                    b.Navigation("PilotReports");

                    b.Navigation("Qualifications");

                    b.Navigation("TechnicalReports");
                });

            modelBuilder.Entity("AirlineApp.Models.Flight", b =>
                {
                    b.Navigation("CrewAssignments");

                    b.Navigation("FlightLogs");

                    b.Navigation("PilotReports");
                });

            modelBuilder.Entity("AirlineApp.Models.TechnicalReport", b =>
                {
                    b.Navigation("SpareParts");
                });

            modelBuilder.Entity("AirlineApp.Models.TrainingEvent", b =>
                {
                    b.Navigation("EmployeeTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
